name: Create Release on Tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenWRT version (e.g., 24.10.5)'
        required: true
        type: string
      targets:
        description: 'Targets (comma-separated, optional)'
        required: false
        type: string
      subtargets:
        description: 'Subtargets (comma-separated, optional)'
        required: false
        type: string


jobs:
  generate-config:
    runs-on: ubuntu-latest
    outputs:
      job-config: ${{ steps.generate-config.outputs.job-config }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Get OpenWRT version from inputs or tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

            if [ -n "${{ inputs.targets }}" ]; then
              echo "TARGETS=${{ inputs.targets }}" >> $GITHUB_ENV
            fi

            if [ -n "${{ inputs.subtargets }}" ]; then
              echo "SUBTARGETS=${{ inputs.subtargets }}" >> $GITHUB_ENV
            fi

          elif [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "VERSION=${{ inputs.tag_name }}" >> $GITHUB_ENV

          else
            echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: npm install

      - name: Generate Job Config
        id: generate-config
        run: node index.js ${{ env.VERSION }} "${{ env.TARGETS }}" "${{ env.SUBTARGETS }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch}} :: ${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}} build"
    runs-on: ubuntu-latest
    needs: generate-config
    strategy:
      matrix:
        build_env: ${{ fromJson(needs.generate-config.outputs.job-config) }}
      fail-fast: false

    steps:
      - name: Checkout AWG source code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyelftools

      - name: Cache OpenWrt SDK
        id: cache-sdk
        uses: actions/cache@v4
        env:
          cache-name: "cache-sdk-${{ matrix.build_env.tag }}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}"
        with:
          path: openwrt-sdk-*/
          key: ${{ runner.os }}-sdk-${{ env.cache-name }}

      - name: Download and extract ImmortalWrt SDK
        run: |
          # Внимательно проверь слэши в конце P1 и P2!
          P1="https://downloads.immortalwrt.org"
          P2="mediatek/filogic/"
          P3="immortalwrt-sdk-24.10.5-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.xz"
          
          echo "Скачиваем SDK по адресу: ${P1}${P2}${P3}"
          wget "${P1}${P2}${P3}" -O sdk.tar.xz
          
          tar -xf sdk.tar.xz
          mv immortalwrt-sdk-* sdk_dir
          rm sdk.tar.xz

      - name: Setup SDK and feeds
        run: |
          cd sdk_dir
          ./scripts/feeds update -a || echo "Ignore feeds error"
          ./scripts/feeds install -a
          cp -r "$GITHUB_WORKSPACE/kmod-amneziawg" package/
          cp -r "$GITHUB_WORKSPACE/amneziawg-tools" package/
          cp -r "$GITHUB_WORKSPACE/luci-proto-amneziawg" package/
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" > .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-amneziawg=y" >> .config
          make defconfig

      - name: Build AmneziaWG packages
        run: |
          cd sdk_dir
          export FORCE_UNSAFE_CONFIGURE=1
          make package/kmod-amneziawg/compile V=s -j$(nproc)
          make package/amneziawg-tools/compile V=s -j$(nproc)
          make package/luci-proto-amneziawg/compile V=s -j$(nproc)

      - name: Prepare artifacts
        run: |
          mkdir -p awgrelease
          find sdk_dir/bin/ -name "*.?pk" -exec cp {} awgrelease/ \;
          ls -la awgrelease/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awgrelease/*.?pk
          tag_name: v${{ matrix.build_env.tag }}
